### ISSUE TITLE
Is bandie.org down?

### ISSUE THREAD

**Issue by Lunarequest** [Bandie/grub2-signing-extension#7]
every time I try to get the gpg key it fails with `gpg: keyserver receive failed: General error` I tried to manually download the key directly but bandie.org troughs an error stating that it isn't a known service

**Comment by Bandie** [comment]
Oh, thanks for telling me. I forgot to set up DNSSEC resigning for bandie.org. It might work now getting it from [here](https://bandie.org/assets/bandie.pub.asc).

Sadly some GPG servers are dead due to key poisoning.. did you try using keys.openpgp.org as keyserver instead?

(Also, I love your avatar.)

**Comment by Lunarequest** [comment]
Oh thanks. i didn't think about the opengpg keys.org server
